### ISSUE TITLE
IOS 10: Photo taken from the camera: Secondary Handler does not get called

### ISSUE THREAD

**Issue by hemantasapkota** [lbrndnr/ImagePickerSheetController#102]
I did a bit of debugging and it seems that in the **handle()** method of **ImagePickerAction** the **numberOfImages** variable is zero despite clicking the **Use Photo** button on the camera.

If i had more time on hand, I'd probably send a PR but this seems like a trivial fix and the author could probably fix is faster than I could.

Thanks

**Comment by lbrndnr** [comment]
Hmm, this is intended. When you want to take a photo it is your responsibility to present/dismiss whatever controller you like. IPSC doesn't really know what you're doing from that point on.

Or did I misunderstand your issue?

**Comment by hemantasapkota** [comment]
Hi, you're right. Looks like I got confused with something else. I'll close this issue. :) :)
