### ISSUE TITLE
"Add Comment"

### ISSUE THREAD

**Issue by scottcc** [lbrndnr/ImagePickerSheetController#104]
Hello Laurin - great library you have here, thanks for sharing it. Love the animations and general structure of the code (I'm at the tip of the `fix-maximum-selection` branch). Just had something of a basic question about the intent/purpose of the two `ImagePickerAction` rows _once at least one image has been selected_. 

From what I can seem to see, both actions will fire the same handler, though we can have separate titles for them. The example usage refers to "Add Comment" which may well be useful, keeping in mind it would apply to N photos. 

In order of importance to me, I'd love to either:

1. Hide/remove that first `ImagePickerAction` _if and only if_ > 0 images have been selected, or
2. Alter the handler that fires for that first row (so I could pop a modal text field to ask for comments, say). Not sure how I'd know when that happened though, nor can I currently get to the `handler: Handler?` instance member as it's both `fileprivate` and a `let` to boot.

Thanks in advance for your (or anyone else's) thoughts.

**Comment by EdenShapiro** [comment]
Hey @scottcc, I'm working on the same issue right now. I tried forking the repo and editing the ImagePickerAction class, but it's gotten more complicated than I'd like. What did you end up doing to fix this issue?

**Comment by scottcc** [comment]
Hi @EdenShapiro! Yeah, I was looking into this a bit more, then saw that the author has moved on to a tray-style version (here: https://github.com/lbrndnr/ImagePickerTrayController ), yet that one is still marked as "WIP Don't use" and hasn't seen a ton of activity... so, I still have the same issue too. Might be interested in forking and fixing though, when I {get back into that area|it gets high enough priority}

**Comment by lbrndnr** [comment]
Heyo everybody,
Sorry for not maintaining either of these projects very much. I'm quite busy with my studies and haven't done a lot of iOS programming lately. I guess it's easiest if you fork the project and continue it by yourself... I can also make you collaborators if you have enough time working on this.

**Comment by scottcc** [comment]
No problem @lbrndnr - I recall my studying days too 👍. Not sure how much time I have available to help, but happy to do so if you feel it's advisable. Certainly this thing with @EdenShapiro would be something I'd like to address in the near/medium term first :)

**Comment by EdenShapiro** [comment]
I might have time to look more closely at it in a couple weeks. I'll post here if I get the "Add comment" working.
