### ISSUE TITLE
Choppy scrolling

### ISSUE THREAD

**Issue by mitchellporter** [lbrndnr/ImagePickerSheetController#62]
Scrolling in the picker's collection view is very choppy.

**Comment by benwu7** [comment]
yea, it feels laggy on my iPhone 6s+

**Comment by love4soul** [comment]
it's because of `requestOptions.synchronous = true`

**Comment by ProjectDent** [comment]
I'm getting this too. I wonder if for the preview you could get a much smaller thumbnail. I think it's probably loading in high-res images, which is why it's losing frames.
