### ISSUE TITLE
Add types to SecondaryHandler

### ISSUE THREAD

**Issue by brightsider** [lbrndnr/ImagePickerSheetController#64]
Can you add type of selected media to SecondaryHandler?
I want to show title like in iMessage -> 1 Video, 1 Photo or 2 objects.

**Comment by lbrndnr** [comment]
Hmm I thought about this a little and decided that this isn't necessary because of the following two reasons:
- You can compute these numbers on your own by looking at the `selectedImageAssets` property
- Nobody else asked for this feature

**Comment by brightsider** [comment]
It's bad :(
