### ISSUE TITLE
Unable to record a video

### ISSUE THREAD

**Issue by codyrotwein** [lbrndnr/ImagePickerSheetController#65]
When I select the Take Photo and Video option, the camera is only set to take photos but not videos. How do I enable this?

I'm calling like this:
`let controller = ImagePickerSheetController(mediaType: .ImageAndVideo)
        controller.addAction(ImagePickerAction(title: NSLocalizedString("Take Photo/Video", comment: "Action Title"), secondaryTitle: NSLocalizedString("Add comment", comment: "Action Title"), handler: { _ in
            presentImagePickerController(.Camera)
            }, secondaryHandler: { _, numberOfPhotos in
                print("Comment \(numberOfPhotos) photos")
        }))`

**Comment by lbrndnr** [comment]
[This SO question](http://stackoverflow.com/questions/3690920/iphone-video-recording-cameracapturemode-1-not-available-because-mediatypes-do) should solve your problem.
