### ISSUE TITLE
expanded status bar pushes modal view down

### ISSUE THREAD

**Issue by Theorian** [lbrndnr/ImagePickerSheetController#68]
expanded status bar pushes modal view down which forces the cancel button to be cut off.
![img_3618](https://cloud.githubusercontent.com/assets/858063/14933688/f7761496-0e32-11e6-8ab9-b5be1e66ec1a.PNG)

**Comment by lbrndnr** [comment]
Transition still not working correctly

**Comment by BalestraPatrick** [comment]
@lbrndnr Where exactly?

**Comment by lbrndnr** [comment]
When the status bar frame changes, the background view isn't aligned to the bounds of the view anymore. Or not in any case.
