### ISSUE TITLE
Select 1 photo

### ISSUE THREAD

**Issue by Theorian** [lbrndnr/ImagePickerSheetController#69]
would it be possible to include the functionality to select a single photo and immediately dismiss the view with that selected photo?

**Comment by colinta** [comment]
I think this would best be accomplished by adding delegate, with a method `didSelectAsset` and `didDeselectAsset`, and then expose the private method `ImagePickerSheetController.cancel`. @lbrndnr Is this a worth-while feature?

**Comment by lbrndnr** [comment]
@colinta That sounds like a great solution!
