### ISSUE TITLE
Getting the specs to run was a bit tricky!

### ISSUE THREAD

**Issue by colinta** [lbrndnr/ImagePickerSheetController#75]
@lbrndnr Are you able to get specs to run easily?  I had to do a ton of work to get them going.
1. Looks like you prefer Carthage, which is 💯 but I'm "old school" and still use Pods, so I added KIF and Quick&Nimble via a Podfile.  So that involved using a workspace and changing `IPSC.xcodeproj/project.pbproj` to be compatible
2. Exposed `waitForViewWithAccessibilityIdentifier` (and friends) in `KIFExtensions.swift`.  Looks like you used to maintain a fork of KIF, but it's been deleted?  These methods are not available in KIF v 3.4.2 (latest)
3. On the upside, it would be easy to get Travis-CI running, I've used it w/ Pods enough to be able to get that going.

Thoughts on all this?  Feels like I must be doing something wrong...

**Comment by colinta** [comment]
You can see what I mean here: 

https://github.com/colinta/ImagePickerSheetController/pull/1

Travis:
https://travis-ci.org/colinta/ImagePickerSheetController/builds/136491975

**Comment by lbrndnr** [comment]
Yeah, looks like I deleted my KIF branch...
I think the problem was that KIF was being KIF and acted up a little so I had to alter a couple methods in order to interact with my control.

Are the tests not running at all using the latest version of KIF?
