### ISSUE TITLE
How to pick Image

### ISSUE THREAD

**Issue by far2an** [lbrndnr/ImagePickerSheetController#76]
i couldnt find the method to get images
i saw a tutorial, he uses getselectedimages but its not there anymore

**Comment by colinta** [comment]
We're using an up-to-date version of this in the Ello app, look in "OmnibarImagePicker.swift" (I think) https://github.com/ello/ello-ios 

I can post more details on Monday (but send a message to me if I don't, I'll likely forget!), when I'm at my computer.
