### ISSUE TITLE
Incompatiable with Xcode 8.0 beta 2

### ISSUE THREAD

**Issue by jondkimball** [lbrndnr/ImagePickerSheetController#77]
Swift sytanx used throughout the project causes compiler issues while running Xcode 8.0 beta 2. Issues range from use of renamed objects (NSPredicate has been renamed to Predicate) to simple syntax changes.

**Comment by colinta** [comment]
To be expected, I think, because of the sweeping changes to Swift in version 3.  We could create a `swift3` branch, not sure what a release schedule would look like, but I think that releasing a new major version after 8.0 leaves beta would be a sensible thing to do.

**Comment by BalestraPatrick** [comment]
You can use the [swift 3 branch](https://github.com/lbrndnr/ImagePickerSheetController/tree/swift3) which should compile with the stable version of Xcode 8 for now.
