### ISSUE TITLE
Cocoapods org not update 0.9.2?

### ISSUE THREAD

**Issue by kevinlee85** [lbrndnr/ImagePickerSheetController#83]
I have searched your release on Cocoapods website, they said the last version is 0.9.1.
Could you make the update happened on Cocoapods?

**Comment by kevinlee85** [comment]
Hi Guys:
Any update?

**Comment by lbrndnr** [comment]
Yes, we will as soon as the swift3 branch will be merged. Sorry about the trouble

**Comment by kylef** [comment]
@lbrndnr It would be great if you could publish the 0.9.2 release into CocoaPods. The `swift3` branch won't work with Swift 2.3 and neither does the latest release on CocoaPods (0.9.1). The 0.9.2 release (not published to CocoaPods) supports Swift 2.3.

**Comment by lbrndnr** [comment]
I've just pushed version 0.9.3 which is compatible with Swift 2.3 and has some additional fixes. I hope this works, let me know if it doesn't.
