### ISSUE TITLE
How about the Swift3 Compatibility?

### ISSUE THREAD

**Issue by kevinlee85** [lbrndnr/ImagePickerSheetController#89]
Do you have plan to upgrade the library to Swift3.0?

**Comment by BalestraPatrick** [comment]
Hey @kevinlee85, we are still working on it in the [swift3](https://github.com/lbrndnr/ImagePickerSheetController/tree/swift3) branch. You can start using it right now and report any issue you encounter.

**Comment by kevinlee85** [comment]
Yes, It working now. Thank you.
