### ISSUE TITLE
The app crash on Xcode8.0 iOS10 within ImagePickerSheetController.

### ISSUE THREAD

**Issue by kevinlee85** [lbrndnr/ImagePickerSheetController#90]
I have encounter crash after Xcode8.0 iOS10 upgrade.
And don't know why?

**Comment by kevinlee85** [comment]
Then I found one solution here: http://stackoverflow.com/questions/37925583/uiimagepickercontroller-crashes-app-swift3-xcode8

We need to add 2 fields in the info.plist as below:

```
<key>NSCameraUsageDescription</key>
<string>Camera usage description</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>Location usage description</string>
```

Then the crash will disappear. Hope that's can help other devs.
Also suggest owner to add those tip to the Swift3.0 branch's readme file.

**Comment by BalestraPatrick** [comment]
Hey, great that you find a solution yourself. We can for sure add the instructions to the README so that people can avoid wasting time on this.
