### ISSUE TITLE
Swift 3.0 branch 

### ISSUE THREAD

**Issue by alexsanderkhitev** [lbrndnr/ImagePickerSheetController#95]
Hello! 
I tried to use this library with Swift 3, but when I tried to install it via cocaopods I got this error [!] Unknown external source parameters for `ImagePickerSheetController`: `{:branch=>"swift3"}`

I wrote like in Podfile 
    pod 'ImagePickerSheetController', branch: 'swift3'

**Comment by lbrndnr** [comment]
I presume cocoapods doesn't support custom branches, at least according to [this question](http://stackoverflow.com/questions/25140362/cocoapods-point-to-a-branch-in-pod-spec)
