### ISSUE TITLE
On the Swift3 branch: Setting .maximumSelection = 1 and then attempting to select multiple images => app crashes

### ISSUE THREAD

**Issue by andreasemento** [lbrndnr/ImagePickerSheetController#98]
fatal error: Index out of range

![screen shot 2016-11-18 at 14 10 35](https://cloud.githubusercontent.com/assets/19686398/20431171/ed8acc0a-ad98-11e6-9a9a-42a13d97b904.png)

**Comment by hitman1711** [comment]
hey did someone fixed this issue?

**Comment by BalestraPatrick** [comment]
I have opened a [PR](https://github.com/lbrndnr/ImagePickerSheetController/pull/99) with a fix.

**Comment by jeroenleenarts** [comment]
I reviewed the provided PR and commented on it. It is 👎. But I did try and indicate what I think is the true bug fix.

**Comment by kevinlee85** [comment]
I have met the same issue here, and have tried BalestraPatrick's PR. But unfortunately BalestraPatrick's branch have swift3 compatibility issue.

**Comment by kevinlee85** [comment]
@jeroenleenarts Have you found one official solution for this issue?

**Comment by joekw** [comment]
I'd love a fix for this

**Comment by Yetispapa** [comment]
Any update on this?
